name: Publish Release

env:
  APP_NAME: gh-issue-creator

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gh-issue-creator
            asset_name: gh-issue-creator-linux-amd64
          - os: windows-latest
            artifact_name: gh-issue-creator.exe
            asset_name: gh-issue-creator-windows-amd64
          - os: macos-latest
            artifact_name: gh-issue-creator
            asset_name: gh-issue-creator-macos-amd64

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Release
        run: cargo build --release

      - name: Generate release notes
        id: release_notes
        run: |
          RELEASE_NOTES=$(git tag -l --format='%(contents)' ${{ github.ref }})
          echo "$RELEASE_NOTES" > RELEASE_NOTES.md
        shell: bash

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          body_from_file: ./RELEASE_NOTES.md
