name: Build and Release Rust App

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable  # Specify the desired Rust version here, e.g., "1.55.0"

    - name: Build Rust app
      run: cargo build --release

    - name: Archive Artifacts
      run: |
        mkdir artifacts
        cp target/release/gh-issue-creator artifacts/
        tar czvf gh-issue-creator.tar.gz artifacts/
      working-directory: ${{ github.workspace }}

    - name: Set Git User Identity
      run: |
        git config user.email "yahyabutt2020@gmail.com"
        git config user.name "yahya-gis"
      working-directory: ${{ github.workspace }}

    - name: Create Git Tag
      run: git tag -a v1.0 -m "Release v1.0"  # Replace "v1.0" and the message with your version and release message
      working-directory: ${{ github.workspace }}

    - name: Push Git Tag
      run: git push origin v1.0  # Replace "v1.0" with the same tag you created
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./gh-issue-creator.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release URL
      id: release_url
      run: |
        echo "::set-output name=url::${{ steps.create_release.outputs.html_url }}"

    - name: Display Release URL
      run: |
        echo "Release URL is: ${{ steps.release_url.outputs.url }}"
